name: Ejemplo de prueba de k6 en Docker

on:
  push:
    branches:
      - main

jobs:
  k6-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Ejecutar prueba de k6 en Docker
      uses: docker://loadimpact/k6:latest
      with:
        args: run tests/k6/script.js 
