name: Ejecutar pruebas k6 en contenedor Docker

on: [push]

jobs:
  k6-docker:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Ejecutar pruebas k6 en contenedor Docker
      uses: docker://loadimpact/k6:latest
      with:
        args: run $(pwd)/tests/k6/script.js
