name: Serenity Tests Build

on:
  push:
    branches: main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Serenity Test Repo
      uses: actions/checkout@v2
      with:
        repository: AdrianJPT/Netbox-Zabbix-Integration_TEST_SERENITY
        path: Netbox-Zabbix-Integration_TEST_SERENITY
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
