name: Serenity Tests Build
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Serenity Test Repo
      uses: actions/checkout@v3
      with:
        repository: 'AdrianJPT/Netbox-Zabbix-Integration_TEST_SERENITY'
      
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
     
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
      
  # Create a symbolic link to index.html
    - name: Create Symbolic Link
      run: |
        cd ${{ github.workspace }}
        ln -s target/site/serenity/index.html target/site/serenity-report.html

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Serenity-Report
        path: target/site/

